### ISSUE TITLE
Close button disappearing + Duplicate trade whispers not blocked

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Helper#27] opened 2017-03-04 01:23 UTC
Changing the button placement under TradesGUI does not save. If I click "Preview" it shows my changes but when someone starts a trade the window reverts to default. I did hit apply settings. For reference I was trying to change "Thank You" to small and then put Trade Request next to it.

Also could you add the "X" button in the main window back to close the current tab. When people message multiple times on the same item I can only close the extra tabs by clicking "Sold It"
Edit: I noticed in a previous release you mentioned that multiple messages shouldn't be added in the queue. That feature is definitely not working.

**Comment by lemasato** [comment] 2017-03-04 14:51
Currently, for the custom button changes to take place, you need to reload the script.  
What do you mean adding the X button back? The button to close the currently active tab is still there. Does it not appear for you? [(Screenshot)](https://raw.githubusercontent.com/lemasato/POE-Trades-Helper/master/Screenshots/GUI%20Trades%20-%20Active.png)  
&nbsp;  
>Edit: I noticed in a previous release you mentioned that multiple messages shouldn't be added in the queue. That feature is definitely not working.

The features only prevents from having duplicate of the same trade request **from the same buyer**. If someone else sends you a whisper about the same item, it will still be added to the queue.

**Comment by rushtothesun** [comment] 2017-03-04 17:16
The X was not there for me. I was wondering what happened since in previous revisions it has been there. I didn't reload the script so that may be why the button changes didn't take place. 

For the duplicates I had the same buyer message me three times to buy my elemental focus gem. After completing the trade there were still two more tabs from him on the same item and then when I went to hit the X to close the tab I noticed it wasn't there. I'll try it again when I get home.

**Comment by rushtothesun** [comment] 2017-03-04 17:59
Okay so running the script again fixed the button issue. For the "X" loading the first time it shows up. I clicked on TradeGUI changed a button to a different size, hit preview, and now the "X" is gone when someone whispers me.

**Comment by lemasato** [comment] 2017-03-04 19:41
1.8.3 has been released, this issue should be fixed now.  
Thanks for your testings!

**Comment by rushtothesun** [comment] 2017-03-04 20:44
Using the new version I had someone spam whisper me and it looks like the duplicate trades are blocked now. I'll let you know if it happens again.

Also forgot to say that the UI design is pretty neat. Much more thematic than the old white box and less straining on my eye.

**Comment by rushtothesun** [comment] 2017-03-05 15:20
So I may have found another issue with the close button. I went afk and came back with a bunch a trade tabs. I closed them all out with the "X" button and now when someone messages me the info is blank:
https://puu.sh/uvapt/d65b87d554.png

**Comment by lemasato** [comment] 2017-03-13 09:41
The blank trades issue is fixed as 1.8.4.  
Thanks for your reports!

**Closed by lemasato** 2017-03-13 09:41 UTC
