### ISSUE TITLE
Key Macro Delay 

### ISSUE THREAD

**Issue by damoochie** [lemasato/POE-Trades-Helper#19] opened 2017-02-08 06:48 UTC
Hello, firstly, great additions to an already handy poe extension. But the latest version has introduced a delay when executing a macro. I have changed nothing else in my setup so hopefully you can find the problem on your end. Thx for all you do

**Comment by lemasato** [comment] 2017-02-08 15:21
I haven't made any change that should affect the hotkeys.  
Could you make sure the issue is specific to 1.7 by downloading the [1.6.1 here](https://github.com/lemasato/POE-Trades-Helper/releases/download/1.6.1/POE-Trades-Helper.exe)?  

If you are having an issue where the tool is automatically updating, [please refer to the wiki here](https://github.com/lemasato/POE-Trades-Helper/wiki/FAQ#i-want-to-stay-on-an-older-version-but-it-keeps-updating-itself)

**Comment by damoochie** [comment] 2017-02-08 15:50
Thx for the reply. Using the previous version makes it instantly execute my macros again with no delay. I'm happy to provide more information if necessary. Will revert to 1.61 in the meantime though thx

**Comment by lemasato** [comment] 2017-02-09 14:21
How long is the delay?  

[Could you try the versions provided in the .zip file here?](https://github.com/lemasato/POE-Trades-Helper/raw/master/_Testings/Hotkeys%20Delay/Hotkeys%20Delay.zip)

**Comment by damoochie** [comment] 2017-02-10 15:21
I tried all three versions provided but unfortunately they all had the delay (which is about half a second delay). Version 1.61 still works great though....

**Comment by lemasato** [comment] 2017-02-11 16:50
Thank you for your testings.  
I suspect the delay to be due to the pre-rendering of the Trades GUI.  
&nbsp;  
[Could you try the versions provided in the .zip file here?](https://github.com/lemasato/POE-Trades-Helper/raw/master/_Testings/Hotkeys%20Delay/Hotkeys%20Delay.zip)

**Comment by damoochie** [comment] 2017-02-12 03:11
Alrighty! So, the first one had the delay (seemed really bad too) but the next two were perfect. Thankyou again for your efforts.

**Comment by lemasato** [comment] 2017-02-12 14:43
Thank you again. Results went as expected.  
If you don't mind, could you tell me your CPU?

**Comment by damoochie** [comment] 2017-02-12 21:07
![cpu](https://cloud.githubusercontent.com/assets/13886692/22866038/0591515a-f1bb-11e6-9478-d7fbe1f904df.jpg)

**Comment by lemasato** [comment] 2017-02-13 05:17
This issue should be fixed as of 1.7.3!  
Please, update to the latest version and report back.

**Comment by damoochie** [comment] 2017-02-13 10:37
You did it! Thanks a bunch <3

**Closed** 2017-02-13 13:00 UTC
